# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stockApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stockApp

  target 'stockApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-config', :path => '../node_modules/react-native-config'

  end

  target 'stockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_frameworks!

  pod 'SwiftyJSON', '3.1.4'      # 4.0.0
  pod 'Charts', '3.0.3'          # 3.1.1

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

end
